name 'mben-motd'
version '0.1.0'
source 'git://github.com/mben/puppet-module-motd.git'
author 'mben'
license 'Apache 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/mben/puppet-module-motd'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
